spring:
  application:
    name: university-management
  datasource:
    url: jdbc:mysql://localhost:3306/university_demos
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
      org.springframework.data.jpa.repository: DEBUG

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: lgwc ajdp xxjj cyuq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  secret:
    key: ${KEY}

  email:
    fromEmail: ${FROM_EMAIL}

  ALGORITHM: ${ALGORITHM}


